### ISSUE TITLE
Does not include mobx

### ISSUE THREAD

**Issue by jokull** [dooboolab/dooboo-expo#19]
Either description is wrong, or mobx is missing from the boilerplate.

**Comment by hyochan** [comment]
Hey sorry for this. This has been deprecated since the rise of `react-hook`. Mobx actually works well with OOP and not functional.

If you still want to see the deprecated repo you can see [here](https://github.com/dooboolab/dooboo-expo/blob/ts/src/stores/appStore.ts). I'll update the doc.

Also, try using our CLI tool [dooboo-cli](https://www.google.com/search?q=dooboo-cli&rlz=1C5CHFA_enKR865KR867&oq=dooboo-cli&aqs=chrome..69i57j69i60l2.2880j0j7&sourceid=chrome&ie=UTF-8) if you are interested in our work. We also have [medium blog](https://medium.com/dooboolab/announcing-dooboo-cli-v3-5c9fceeb2ac4) for this.
